import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import ThemeSwitcherButton from "@/components/ui/ThemeSwitcherButton/ThemeSwitcherButton";
import NextUIProvider from "@/providers/nextui-provider";
import ThemeProvider from "@/providers/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NextUIProvider className="w-screen h-screen flex relative">
            {children}
            <ThemeSwitcherButton className="absolute bottom-10 right-10" />
          </NextUIProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
